{% set name = "hello_conda" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../src

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed"

requirements:
  host:
    - pip
    - python
    - requests
  run:
    - python
    - requests